steps:

# Copy files
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
- task: CopyFiles@2
  inputs:
    sourceFolder: 'Deploy'
    #contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)
    #cleanTargetFolder: false # Optional
    overWrite: true # Optional
    #flattenFolders: false # Optional
    #preserveTimestamp: false # Optional

# - task: ArchiveFiles@2
#   displayName: 'Archive Files'
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
#     includeRootFolder: false
#     archiveType: zip
#     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#     replaceExistingArchive: true

# - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#   displayName: Build
#   artifact: drop

# - publish: $(Build.Repository.LocalPath)/Deploy
#   displayName: Copy ARM Templates
#   artifact: deploy  