name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*

  paths:
    exclude:
     - doc
     - ReadME.md

pr:
  branches:
    include:
    - master

variables:
- name: vmImage
  value: 'windows-latest'

stages:
- stage: Setup Templates
  jobs:
  - job: 'Setup Templates'
    pool:
      vmImage: ${{variables.vmImage}}
    steps:
    - template: 'publishartifacts.yaml'

- stage: DEV
  dependsOn: ['Setup Templates']
  jobs:
  - deployment: DEV
    # variables:
    # - template: 'variables/variables.dev.yaml'
    pool:
        vmImage: ${{variables.vmImage}}
    environment: NonProd
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yaml'